USE demo;
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id       INT(11) AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(64)        NOT NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

DROP TABLE IF EXISTS salary;
CREATE TABLE salary (
  id     INT         NOT NULL PRIMARY KEY,
  name   VARCHAR(20) NOT NULL,
  salary DOUBLE      NOT NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

INSERT INTO salary VALUES (1,'A',1000.00),(2,'B',1000.00);

SELECT * FROM salary;
