USE demo;
DROP TABLE IF EXISTS user;
CREATE TABLE user(
  id int(11) AUTO_INCREMENT PRIMARY KEY ,
  username VARCHAR(64) UNIQUE NOT NULL ,
  password VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;